name: Daily Postman Collections Test

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta diariamente a la medianoche UTC
  workflow_dispatch:       # Permite ejecución manual

jobs:
  run-postman-collections:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Especifica la versión de Node.js

    - name: Install Newman and jq
      run: |
        npm install -g newman
        sudo apt-get update && sudo apt-get install -y jq

    - name: Load and Run Postman Collections
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        # Lee el archivo JSON y recorre cada colección
        cat postman-config.json | jq -c '.[]' | while read -r config; do
          collection=$(echo "$config" | jq -r '.collection')
          environment=$(echo "$config" | jq -r '.environment')
          
          echo "Running collection: $collection with environment: $environment"
          newman run "$collection" -e "$environment" --reporters cli,junit --reporter-junit-export "results.xml" || exit 1
        done

    - name: Send Notification on Failure
      if: failure()
      run: |
        echo "Sending failure notification"
        curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"🚨 Error in Postman Collections Test in GitHub Actions 🚨"}' \
          $SLACK_WEBHOOK_URL

    - name: Send Email Notification on Failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "🚨 Postman Test Failure in GitHub Actions 🚨"
        body: "One or more Postman collections failed. Please check the workflow logs."
        to: your_email@example.com
        from: GitHub Actions <github-actions@example.com>
